configs:
  - name: GRU Copy
    task:
      class_name: CopyTask
      train_kwargs:
        vector_size: 8
        min_sequence_length: 1
        max_sequence_length: 21
      validation_kwargs:
        vector_size: 8
        min_sequence_length: 100
        max_sequence_length: 101
    model:
      class_name: GRUAgent
      kwargs:
        input_size: 8
        state_size: 64
        output_size: 8
    repeat: 5
  - name: NTM Copy
    task:
      class_name: CopyTask
      train_kwargs:
        vector_size: 8
        min_sequence_length: 1
        max_sequence_length: 21
      validation_kwargs:
        vector_size: 8
        min_sequence_length: 100
        max_sequence_length: 101
    model:
      class_name: NTMAgent
      kwargs:
        input_size: 8
        state_size: 64
        num_memory_banks: 128
        memory_bank_size: 64
        max_shift: 5
        output_size: 8
    repeat: 5
